[workspace]
members = ["crates/flux-core", "crates/fluxd", "xtask"]
resolver = "2"

[workspace.package]
version = "0.9.0"
edition = "2021"
rust-version = "1.93"
license = "GPL-3.0-only"
repository = "https://github.com/Chth1z/Flux-rs"

[workspace.dependencies]
flux-core = { path = "crates/flux-core" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
toml = "0.8"
libc = "0.2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
